### ISSUE TITLE
Testing the wildfly-jar-maven-plugin with a custom core and WildFly master

### ISSUE THREAD

**Issue by jamezp** [wildfly/snapshot-ci#11]
```
name: Latest WildFly Core with WildFly for WildFly JAR Maven Plugin
components:
  # Add as many components as you like here, adjusting name (of the repo), org and branch
  # If your component has dependencies set them up with component name and version property
  - name: wildfly-core
    org: jamezp
    branch: 'WFCORE-5232'
    env: 
      MAVEN_TEST_PARAMS: -DskipTests
  - name: wildfly
    org: wildfly
    branch: 'master'
    env: 
      MAVEN_TEST_PARAMS: -DskipTests
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
  - name: wildfly-jar-maven-plugin
    org: wildfly-extras
    branch: 'master'
    mavenOpts: '-Dversion.microprofile.bom=21.0.1.Final -Dversion.server.bom=21.0.1.Final'
    dependencies:
      - name: wildfly
        property: version.wildfly

```
