### ISSUE TITLE
[ELY-2001] Security Realms should support specifying the charset and encoding for credentials.

### ISSUE THREAD

**Issue by SoniaZaldana** [wildfly/snapshot-ci#13]
```
name: ELY-2001 Security Realms charset and encoding support for credentials
components:
  - name: wildfly-elytron
    org: SoniaZaldana
    branch: 'ELY-2001'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: SoniaZaldana
    branch: 'WFCORE-5027'
    dependencies:
      - name: wildfly-elytron
        property: version.org.wildfly.security.elytron
  - name: wildfly
    org: SoniaZaldana
    branch: 'WFLY-13625'
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
