### ISSUE TITLE
[ELY-2024] Elytron server-ssl-context allowed protocols

### ISSUE THREAD

**Issue by SoniaZaldana** [wildfly/snapshot-ci#14]
```
name: ELY-2024 Elytron server-ssl-context allowed protocols.
components:
  - name: wildfly-elytron
    org: SoniaZaldana
    branch: 'ELY-2024'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: SoniaZaldana
    branch: 'WFCORE-5145'
    dependencies:
      - name: wildfly-elytron
        property: version.org.wildfly.security.elytron
  - name: wildfly
    org: SoniaZaldana
    branch: 'WFLY-13916'
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
