### ISSUE TITLE
[WFLY-12215] Encrypted Expression Resolution

### ISSUE THREAD

**Issue by darranl** [wildfly/snapshot-ci#17]
````
name: WFLY-12215 Encrypted Expression Resolution
components:
  - name: wildfly-elytron
    org: darranl
    branch: ELY-1842
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: darranl
    branch: WFCORE-4360
    dependencies:
      - name: wildfly-elytron
        property: version.org.wildfly.security.elytron
  - name: wildfly
    org: darranl
    branch: master
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
````

2021-02-05 Try another run.
2021-02-17 Run with latest set of changes.
