### ISSUE TITLE
 WFLY-14277 Eclipse MP REST Client 2.0 Integration Test

### ISSUE THREAD

**Issue by jamezp** [wildfly/snapshot-ci#19]
```
name: WFLY-14277 Eclipse MP REST Client 2.0
components:
  - name: Resteasy
    org: jamezp
    branch: "RESTEASY-2832"
    mavenOpts: -DskipTests
  - name: wildfly
    org: jamezp
    branch: "resteasy-mp4-client"
    dependencies:
      - name: Resteasy
        property: version.org.jboss.resteasy
```
