### ISSUE TITLE
[ELY-2101] Upgrade Apache sshd-common to a version that depends on slf4j 1.7.30

### ISSUE THREAD

**Issue by SoniaZaldana** [wildfly/snapshot-ci#27]
```
name: ELY-2101 Upgrade Apache sshd-common to a version that depends on slf4j 1.7.30
components:
  - name: wildfly-elytron
    org: SoniaZaldana
    branch: 'ELY-2101'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: SoniaZaldana
    branch: 'master'
    dependencies:
      - name: wildfly-elytron
        property: version.org.wildfly.security.elytron
  - name: wildfly
    org: SoniaZaldana
    branch: 'master'
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
