### ISSUE TITLE
Resolve Expressions from Env Vars

### ISSUE THREAD

**Issue by kabir** [wildfly/snapshot-ci#28]
```
name: Resolve Expressions from Env Vars
components:
  # Add as many components as you like here, adjusting name (of the repo), org and branch
  # If your component has dependencies set them up with component name and version property
  - name: jboss-dmr
    org: kabir
    branch: 'resolution-policy'
    mavenOpts: -DskipTests
  # components - end

  # Our target/main components. Adjust the dependencies to pull in the prior ones
  - name: wildfly-core
    org: kabir
    branch: master
    dependencies:
      - name: jboss-dmr
        property: version.org.jboss.jboss-dmr
  - name: wildfly
    org: wildfly
    branch: master
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
