### ISSUE TITLE
ELY-2078 Add encryption and integrity support to FilesystemSecurityRealm

### ISSUE THREAD

**Issue by Ashpan** [wildfly/snapshot-ci#30]
```
name: Add encryption and integrity support to Filesystem Security Realm
components:
  - name: wildfly-elytron
    org: Ashpan
    branch: 'ELY-2078'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: Ashpan
    branch: 'WFCORE-5530'
    dependencies:
      - name: wildfly-elytron
        property: version.org.wildfly.security.elytron
  - name: wildfly
    org: Ashpan
    branch: 'WFLY-15075'
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
