### ISSUE TITLE
Test JSTL 3.0.2 (SE 17)

### ISSUE THREAD

**Issue by bstansberry** [wildfly/snapshot-ci#38]
```
name: JSTL 3.0.2
components:
  - name: jakarta-tags
    org: bstansberry
    branch: 'test_impl_302'
    mavenOpts: -DskipTests
  - name: wildfly
    org: wildfly
    branch: main
    java-version: 17
    dependencies:
      - name: jakarta-tags
        property: version.org.glassfish.web.jakarta.servlet.jsp.jstl
```
