### ISSUE TITLE
XNIO and Remoting only

### ISSUE THREAD

**Issue by kabir** [wildfly/snapshot-ci#5]
```
name: XNIO and Remoting
components:
  - name: xnio
    org: kabir
    branch: '3.8'
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: kabir
    branch: '5.0'
    mavenOpts: -DskipTests
    dependencies:
      - name: xnio
        property: xnio.version
```
