### ISSUE TITLE
Remoting into Full

### ISSUE THREAD

**Issue by kabir** [wildfly/snapshot-ci#6]
```
name: Remoting into Full
components:
  - name: jboss-remoting
    org: jboss-remoting
    branch: '5.0'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: master
    dependencies:
      - name: jboss-remoting
        property: version.org.jboss.remoting
  - name: wildfly
    org: wildfly
    branch: master
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
