### ISSUE TITLE
Test Remoting PR #236 REM3-371 in wildfly-core

### ISSUE THREAD

**Issue by gaol** [wildfly/snapshot-ci#8]
```
name: Test Remoting PR #236 REM3-371 in wildfly-core
components:
  - name: jboss-remoting
    org: yersan
    branch: 'REM3-371'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: master
    dependencies:
      - name: jboss-remoting
        property: version.org.jboss.remoting
```
